In [1]:
import numpy as np

In [2]:
temps = np.array([20,25,30,35])
print(temps)

[20 25 30 35]


The numbers have no commas now, and this is called numpy array .

Using your temps array, multiply every number by 2 and print the result.
Hint: it's the same shape as the example, just swap + 5 for * 2 (in Python, * means multiply).


In [2]:
import numpy as np
temps = np.array([20,25,30,35])
for temp in temps:
    print(temp*2)


40
50
60
70


               The above code works but the whole point of using numpy is that we don't have to use loops! A loop is slower than numpy, when we have to deal with large data sets, the loop would crawl down when numpy would fly.
               therefore: the valid code for numpy is below                

In [3]:
print(temps*2)

[40 50 60 70]


In [5]:
print(temps[2])

30


SLICING is the concept of grabbing a range of numbers not just one index. [start:stop]

In [7]:
print(temps[0:3])

[20 25 30]


The colon is the range, no colon [0] -> single number, if colon : it is a range [0:3]

2D array mean. I put list inside of a list. 

In [11]:
grades = np.array([[25,30], 
                [35,40],
                [45,50]])
print(grades)

[[25 30]
 [35 40]
 [45 50]]


In [13]:
data = np.array([[1,2,3],
         [4,5,6]])
print(data)

[[1 2 3]
 [4 5 6]]


[                    ← the OUTER bracket = the whole table (the register)
   [1, 2, 3],        ← an inner bracket = row 1
   [4, 5, 6]         ← an inner bracket = row 2
]                    ← close the outer bracket

In [1]:
import numpy as np

In [4]:
data = np.array([[2,3,4],
                [5,6,7]])
print(data[0,2]) #row then inside the row count the column, which is after comma.

4


In [12]:
data = np.array([2,3,4,5,6,7])
print(sum(data))
print(np.mean(data))
print(min(data))
print(max(data))

27
4.5
2
7


Make a new array called scores with these numbers: 10, 20, 30, 40, 50. Then print:

their sum
their average (mean)
the biggest one

In [5]:
import numpy as np
scores = np.array([72, 45, 88, 91, 38, 67, 55, 80])
print(np.sum(scores))
print(np.mean(scores))
print(np.max(scores))
print(scores[4:8])
print(scores[:4])
print(scores[-4:])
print(scores[0:-4])

536
67.0
91
[38 67 55 80]
[72 45 88 91]
[38 67 55 80]
[72 45 88 91]


SHAPES: When you get a real dataset, the first thing you ask is "how big is it?" — how many rows, how many columns? NumPy answers with .shape.
Notice something new: there's no np. and no brackets here. shape isn't a tool you call — it's a piece of information attached to the array itself. You ask the array about itself

In [9]:
print(np.shape(scores)) #1d array, counts item in the array, then leaves column side empty. [row, column]

(5,)


In [1]:
import pandas as pd

Meeting the Series container of Pandas

A Series is like a NumPy array, but with one upgrade: each value has a label. A plain array just has positions (0, 1, 2...). A Series has positions and names you choose.

In [3]:
marks = pd.Series([85,90,70])
print(marks)

0    85
1    90
2    70
dtype: int64


In [5]:
import numpy as np
marks = np.array([85,90,70])
print(marks)

[85 90 70]


In [6]:
prices = pd.Series([100,250,80], index=["Pen","Bag", "Book"])
print(prices)


Pen     100
Bag     250
Book     80
dtype: int64


Step 2 — your task:
Build a DataFrame called products with these three columns:

"Item" → "Pen", "Bag", "Book"
"Price" → 100, 250, 80
"Stock" → 50, 20, 100

Then print it.
Use the shape above as your guide — a dictionary inside pd.DataFrame({ ... }), each column a key with a list. Type it, run it, and paste back your code and output. 🙂

In [3]:
import pandas as pd
products = pd.DataFrame({
    "Item": ["Pen","Bag","Book"],
    "Price": [100, 250, 80],
    "Stock": [50, 20, 100]
})
print(products)

   Item  Price  Stock
0   Pen    100     50
1   Bag    250     20
2  Book     80    100


In [8]:
scores = np.array([10,20,30,40,50])
print(scores[:4])
print(scores[-4:])
print(scores[0:-4])
print(scores[:-4])
print(scores[4:])

[10 20 30 40]
[20 30 40 50]
[10]
[10]
[50]
